version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn global add semantic-release
      - run: yarn install
      - run: yarn test
      - run: semantic-release
